accounts/urls.py
from django.urls import include,path
from . import views

urlpatterns = [
     path("registerUser/", views.registerUser,name="registerUser"),
     path("customerDashboard/", views.customerDashboard,name="customerDashboard"),
     path("sellerDashboard/", views.sellerDashboard,name="sellerDashboard"),
     path("login/", views.login,name="login"),
     path("registerSeller/", views.registerSeller,name="registerSeller"),
     path("logout/", views.logout,name="logout"),
     path("myaccount/", views.myaccounts,name="myaccounts"),
     path("activate/<uidb64>/<token>/", views.activate,name="activate"),
     path("forgot_password/", views.forgot_password,name="forgot_password"),
       path('reset_password_validate/<uidb64>/<token>/',views.reset_password_validation,name="reset_password_validate"),
     path("reset_password/", views.reset_password,name="reset_password"),

      
   
]

dashboard/urls.py
from django.urls import include,path
from . import views

urlpatterns = [
   
    path('dashboardHome/',views.dashboardHome,name='dashboardHome'),
    path('CustomerOrders/',views.CustomerOrders,name='CustomerOrders'),
    path('cutomerreviews/',views.cutomerreviews,name='cutomerreviews'),
    path('userprofile/',views.userprofile,name='userprofile'),
   
]

ecomerce/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include,path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('product/', include('products.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path,include

from . import views

urlpatterns=[
    path("", views.home,name="home"),
    path("contactus/", views.Contactus,name="contactus"),

    
    
    

]  

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager
# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self,first_name,last_name,username,email,phone_number=None,password=None):
        if not email: 
            raise ValueError('User must have an email address')
        if not username:
            raise ValueError('User must have username')
        
        user=self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            phone_number=phone_number,

        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    

    def create_superuser(self,first_name,last_name,username,email,password=None):
        user=self.create_user(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            password = password
        )
         
        user.is_superuser=True
        user.is_staff=True
        user.is_active=True
        user.is_admin=True
        user.save(using=self._db)

        return user
          
        



class User(AbstractBaseUser):
    CUSTOMER=1
    SELLER=2
    ROLE_CHOICE=(
        (SELLER,'SELLER'),
        (CUSTOMER,'CUSTOMER')
    )

    first_name=models.CharField(max_length=50)
    last_name=models.CharField(max_length=50,null=True,blank=True)
    email=models.EmailField(max_length=100,unique=True)
    username=models.CharField(max_length=50)
    phone_number=models.CharField(max_length=14,blank=True,null=True)
    role=models.PositiveSmallIntegerField(choices=ROLE_CHOICE,blank=True,null=True)
    date_joined=models.DateTimeField(auto_now_add=True)
    last_login=models.DateTimeField(auto_now=True)
    is_admin=models.BooleanField(default=False)
    is_active=models.BooleanField(default=False)
    is_staff=models.BooleanField(default=False)
    is_superuser=models.BooleanField(default=False)

    USERNAME_FIELD='email'
    REQUIRED_FIELDS=['username', 'first_name','last_name']
    objects=UserManager()
    def __str__(self):
        return self.email
    def has_perm(self,perm,obj=None):
        return self.is_admin
    def has_module_perms(self,app_label):
        return True

class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,blank=True,null=True)
    profile_picture=models.ImageField(upload_to='user/profile_picture',blank=True,null=True)
    cover_photo=models.ImageField(upload_to='user/cover_photo',blank=True,null=True)
    adress_line_1=models.CharField(max_length=100,null=True,blank=True)
    adress_line_2=models.CharField(max_length=100,null=True,blank=True)
    country=models.CharField(max_length=20,null=True,blank=True)
    state=models.CharField(max_length=20,null=True,blank=True)
    city=models.CharField(max_length=20,null=True,blank=True)
    pin_code=models.CharField(max_length=20,null=True,blank=True)
    lattitude=models.CharField(max_length=20,null=True,blank=True)
    longitude=models.CharField(max_length=20,null=True,blank=True)
    created_at=models.DateTimeField(auto_now_add=True)
    modified_at=models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.user.username
    

dashboard/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('first_name','last_name','username','email','password','phone_number')
    def cleaned(self):
        clean_data = super(UserForm, self).clean()
        password=clean_data.get('password')
        confirm_password=clean_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError('password dosent matched')

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib import messages,auth
from .forms import UserForm
from .models import User,UserProfile
from .utils import detectUser,send_email,send_notification
from seller.forms import SellerForm
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.decorators import login_required
# Create your views here.
def registerUser(request):
    if request.user.is_authenticated:
        messages.warning(request,'You are already logged in...')
        return redirect('home')
    elif request.method=='POST':
        form=UserForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name=form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            phone_number=form.cleaned_data['phone_number']
            user=User.objects.create_user(first_name=first_name,last_name=last_name,username=username,email=email,password=password,phone_number=phone_number)
            user.role=User.CUSTOMER
            user.save()
            email_subject = "Please active your account"
            email_template ="accounts/emails/account_varification.html"
            send_email(request,user,email_subject,email_template)
            messages.success(request,'Your account has been registered successfully,Please check your mail for confirmation')
            return redirect('home')
        else:
            messages.error(request,'Invalid data input')
    else:
        form=UserForm()
    
    context = {
        'form': form,
        
    }
    return render(request,'accounts/RegiserUser.html',context)



def registerSeller(request):
    if request.user.is_authenticated:
        messages.waring(request,'You are already logged in')
        return redirect('home')
    elif request.method == 'POST':
        form=UserForm(request.POST)
        seller_form=SellerForm(request.POST,request.FILES)
        if form.is_valid() and seller_form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name=form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            phone_number=form.cleaned_data['phone_number']
            user=User.objects.create_user(first_name=first_name,last_name=last_name,username=username,email=email,password=password,phone_number=phone_number)
            user.role=User.SELLER
            user.save()
            seller=seller_form.save(commit=False)
            seller.user=user

            user_profile=UserProfile.objects.get(user=user)
            seller.user_profile=user_profile
            seller.save()
            email_subject = "Please active your account"
            email_template ="accounts/emails/account_varification.html"
            send_email(request,user,email_subject,email_template)
            messages.success(request,'Your account has been registered successfully,Please check your mail for confirmation')
            return redirect('home')
        else:
            messages.error(request,'Invalid data found')
    else:
        form=UserForm()
        seller_form=SellerForm()
    
    context={
        'form': form,
        'seller_form':seller_form
    }
    return render(request,'accounts/Registerseller.html',context)



def activate(request,uidb64,token):
    try:
        uid=urlsafe_base64_decode(uidb64).decode()
        user=User._default_manager.get(pk=uid)
    except (TypeError,ValueError,User.DoesNotExist):
        user=None
    if user is not None and default_token_generator.check_token(user,token):
        user.is_active=True
        user.save()
        return redirect('login')



def login(request):
    if request.user.is_authenticated:

        messages.warning(request,'You are already logged in')
    elif request.method=='POST':
        email=request.POST['email']
        password=request.POST['password']
        user=auth.authenticate(email=email,password=password)
        if user is not None:
            auth.login(request,user)
            messages.success(request,'sucessfully logged in!!!')
            return redirect('myaccounts')
        else:
            messages.error(request,'Invalid login credentials')
            return redirect('login')
    return render(request,'accounts/login.html')
        
    

         


def logout(request):
    auth.logout(request)
    messages.info(request,'You are logged out!!!')
    return render(request,'accounts/login.html')


@login_required(login_url=login)
def myaccounts(request):
    user=request.user
    redirectUrl=detectUser(user)
    return redirect(redirectUrl)
            
@login_required(login_url=login)
def customerDashboard(request):
    return render(request,'accounts/customerDashboard.html')

@login_required(login_url=login)
def sellerDashboard(request):
    return render(request,'accounts/sellerDashboard.html')


def forgot_password(request):
    if request.method == 'POST':
        email=request.POST['email']
        if User.objects.filter(email=email).exists():
            user=User.objects.get(email__exact=email)
            email_subject="Reset Your password"
            email_template="accounts/emails/reset_password.html"
            send_email(request,user,email_subject,email_template)
            messages.success(request,'Password Reset Link Has been sent to your email address')
            return redirect('login')
        else:
            messages.error(request,"Account doesn't exists")
            return redirect('forgot_password')
    return render(request,'accounts/forgot_password.html')


def reset_password_validation(request,uidb64,token):
    try:
        uid=urlsafe_base64_decode(uidb64).decode()
        user=User._default_manager.get(pk=uid)
    except(TypeError,ValueError,OverflowError,User.DoesNotExist):
        user=None
    
    if user  is not None and default_token_generator.check_token(user,token):
        request.session['uid']=uid
        messages.info(request,'Please reset your password')
        return redirect('reset_password')
    else:
        messages.error(request,'Link expired')
        return redirect('myaccount')
    
def reset_password(request):
    if request.method == 'POST':
        password=request.POST['password']
        confirm_password=request.POST['confirm_password']
        if password==confirm_password:
            pk=request.session.get('uid')
            user=User.objects.get(pk=pk)
            user.set_password(password)
            user.is_active=True
            user.save()
            messages.success(request,'Password changed successfully!!')
            return redirect('login')
        else:
            messages.error(request,'Password not matched')
            return redirect('reset_password')
    return render(request,'accounts/reset_password.html')

dashboard/views.py
from django.shortcuts import render,redirect
from products.models import *
from django.contrib import messages
from products.models import *
from order.models import *
from accounts.models import *
import os
# Create your views here.




def dashboardHome(request):
    return render(request, 'accounts/Dashboard.html')


def CustomerOrders(request):
    user=request.user
    userorder=Order.objects.filter(user=user)
    

     
    context={
        'allorder':userorder,
        

    }
    return render(request, 'accounts/CustomerOrder.html',context)

def cutomerreviews(request):
    user=request.user
    userreivew=Review.objects.filter(author_id=user)
    # Product=Product.objects.get()
    

     
    context={
        'allreview':userreivew,
        

    }
    return render(request, 'accounts/CustomerReivews.html',context)


def userprofile(request):
    user=request.user
    try:
     userprofile=UserProfile.objects.get(user=user)
    except UserProfile.DoesNotExist:
        messages.error(request, "Userprofile does not exist")

    print("user",user)
    print("user",userprofile)
    

    context={
        'user':user,
        'userprofile':userprofile
    }
    if request.method == 'POST' :
        if len(request.FILES) !=0:
 
           if 'profile_picture' in request.FILES:

             os.remove(userprofile.profile_picture.path)
             userprofile.profile_picture=request.FILES['profile_picture']
          

        userprofile.adress_line_1=request.POST.get('adress_line_1')
        userprofile.state=request.POST.get('state')
        userprofile.pin_code=request.POST.get('pin_code')
        userprofile.city=request.POST.get('city')
        user.phone_number=request.POST.get('phone_number')
       
        userprofile.save()
        user.save()
        messages.success(request,"Profile updated SuccessFully!!")
        return render(request, 'accounts/Profile.html',context)

    
    return render(request, 'accounts/Profile.html',context)

templates/accounts/CustomerOrder.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!----======== CSS ======== -->
  <link rel="stylesheet" href="{%static 'css/dashboard.css'%}">

  <!----===== Boxicons CSS ===== -->
  <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>

  <!--<title>Dashboard Sidebar Menu</title>-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
</head>

<body>
  <nav class="sidebar close">
    <header>
      <div class="image-text">
        <span class="image">
          <img src="logo.png" alt="">
        </span>

        <div class="text logo-text">
          <span class="name">Welcome</span>
          <span class="profession">{{user.username}}</span>
        </div>
      </div>

      <i class='bx bx-chevron-right toggle'></i>
    </header>

    <div class="menu-bar">
      <div class="menu">

        <li class="search-box">
          <i class='bx bx-search icon'></i>
          <input type="text" placeholder="Search ...">
        </li>

        <ul class="menu-links">
          <li class="nav-link">
            <a href="{%url 'home'%}">
              <i class='bx bx-home-alt icon'></i>
              <span class="text nav-text">Back To Home</span>
            </a>
          </li>

          <li class="nav-link">
            <a href="{%url 'dashboardHome'%}">
              <i class='bx bx-home-alt icon'></i>
              <span class="text nav-text">Dashboard</span>
            </a>
          </li>

          <li class="nav-link">
            <a href="{%url 'CustomerOrders'%}">
              <i class='bx bx-bar-chart-alt-2 icon'></i>
              <span class="text nav-text">My Orders</span>
            </a>
          </li>

          <li class="nav-link">
            <a href="#">
              <i class='bx bx-bell icon'></i>
              <span class="text nav-text">Notifications</span>
            </a>
          </li>

          <li class="nav-link">
            <a href="#">
              <i class='bx bx-pie-chart-alt icon'></i>
              <span class="text nav-text">Analytics</span>
            </a>
          </li>

          <li class="nav-link">
            <a href="#">
              <i class='bx bx-heart icon'></i>
              <span class="text nav-text">Likes</span>
            </a>
          </li>

          <li class="nav-link">
            <a href="#">
              <i class='bx bx-wallet icon'></i>
              <span class="text nav-text">Wallets</span>
            </a>
          </li>

        </ul>
      </div>

      <div class="bottom-content">
        <li class="">
          <a href="#">
            <i class='bx bx-log-out icon'></i>
            <span class="text nav-text">Logout</span>
          </a>
        </li>

        <li class="mode">
          <div class="sun-moon">
            <i class='bx bx-moon icon moon'></i>
            <i class='bx bx-sun icon sun'></i>
          </div>
          <span class="mode-text text">Dark mode</span>

          <div class="toggle-switch">
            <span class="switch"></span>
          </div>
        </li>

      </div>
    </div>

  </nav>

  <section class="home">
    
    
    <div class="text">
        <h2 class="text-center">
        Welcome {{user.username}}
    </h2>
    <h2 class="text-center">
       All Orders
    </h2>
   <!-- Orders Start here -->
   <table class="table table-striped table-primary table-bordered border-primary">
    <thead>
      <tr>
        <th scope="col">#OrderId</th>
        <th scope="col">Product Name</th>
        <th scope="col">Adress</th>
        <th scope="col">Phone No</th>
        <th scope="col">Status</th>
        <th scope="col">Order Date</th>
        <th scope="col">Price</th>
        <th scope="col">Payment</th>
      </tr>
    </thead>
    <tbody>
        {%for order in allorder %}
        <tr>
            <th scope="row">{{order.id}}</th>
            <td>{{order.product.product_name}}</td>
            <td>{{order.adress}}</td>
            <td>{{order.phone_no}}</td>
            <td>
                {% if order.status%}
                
                <button type="button" class="btn btn-success">Completed</button>
                {% else %}
                <button type="button" class="btn btn-danger">Pending</button>


                {%endif%}


            </td>
            <td>{{order.date_order}}</td>
            <td>${{order.price}}</td>
            <td>{{order.payment_Type}}</td>
          </tr>

        {%endfor%}
     
    
    </tbody>
  </table>

   <!-- order end here -->
</div>
   
  </section>

  <script>
    const body = document.querySelector('body'),
      sidebar = body.querySelector('nav'),
      toggle = body.querySelector(".toggle"),
      searchBtn = body.querySelector(".search-box"),
      modeSwitch = body.querySelector(".toggle-switch"),
      modeText = body.querySelector(".mode-text");
    toggle.addEventListener("click", () => {
      sidebar.classList.toggle("close");
    })
    searchBtn.addEventListener("click", () => {
      sidebar.classList.remove("close");
    })
    modeSwitch.addEventListener("click", () => {
      body.classList.toggle("dark");
      if (body.classList.contains("dark")) {
        modeText.innerText = "Light mode";
      } else {
        modeText.innerText = "Dark mode";
      }
    });
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

</body>

</html>

templates/accounts/Profile.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!----======== CSS ======== -->
  <link rel="stylesheet" href="{%static 'css/dashboard.css'%}">
  <link rel="stylesheet" href="{%static 'css/profile.css'%}">
  <!-- Font Awesome -->
  <link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css"
  rel="stylesheet"
/>
  <!----===== Boxicons CSS ===== -->
  <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>
  <!-- bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- bootstrap -->

  <!--<title>Dashboard Sidebar Menu</title>-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <style>
		body {
			margin: 0;
		}
		
		.container {
			display: flex;
			justify-content: center;
			align-items: center;
		
		}
	</style>
<!-- CSS alertify -->
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
<!-- Default theme -->
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>
</head>

<body>
  <nav class="sidebar close">
    <header>
      <div class="image-text">
        <span class="image">
          <img src="logo.png" alt="">
        </span>

        <div class="text logo-text">
          <span class="name">Welcome</span>
          <span class="profession">{{user.username}}</span>
        </div>
      </div>

      <i class='bx bx-chevron-right toggle'></i>
    </header>

    <div class="menu-bar">
      <div class="menu">

        <li class="search-box">
          <i class='bx bx-search icon'></i>
          <input type="text" placeholder="Search ...">
        </li>

        <ul class="menu-links">
          <li class="nav-link">
            <a href="{%url 'home'%}">
              <i class='bx bx-home-alt icon'></i>
              <span class="text nav-text">Back To Home</span>
            </a>
          </li>

          <li class="nav-link">
            <a href="{%url 'dashboardHome'%}">
              <i class='bx bx-home-alt icon'></i>
              <span class="text nav-text">Dashboard</span>
            </a>
          </li>

          <li class="nav-link">
            <a href="{%url 'CustomerOrders'%}">
              <i class='bx bx-bar-chart-alt-2 icon'></i>
              <span class="text nav-text">My Orders</span>
            </a>
          </li>

          <li class="nav-link">
            <a href="#">
              <i class='bx bx-bell icon'></i>
              <span class="text nav-text">Notifications</span>
            </a>
          </li>

          <li class="nav-link">
            <a href="#">
              <i class='bx bx-pie-chart-alt icon'></i>
              <span class="text nav-text">Analytics</span>
            </a>
          </li>
        
          

          <li class="nav-link">
            <a href="{%url 'cutomerreviews'%}">
              <i class='bx bx-heart icon'></i>
              <span class="text nav-text">Reviews</span>
            </a>
          </li>

          <li class="nav-link">
            <a href="#">
              <i class='bx bx-user icon'></i>
              <span class="text nav-text">Profile</span>
            </a>
          </li>

        </ul>
      </div>

      <div class="bottom-content">
        <li class="">
          <a href="#">
            <i class='bx bx-log-out icon'></i>
            <span class="text nav-text">Logout</span>
          </a>
        </li>

        <li class="mode">
          <div class="sun-moon">
            <i class='bx bx-moon icon moon'></i>
            <i class='bx bx-sun icon sun'></i>
          </div>
          <span class="mode-text text">Dark mode</span>

          <div class="toggle-switch">
            <span class="switch"></span>
          </div>
        </li>

      </div>
    </div>

  </nav>

  <section class="home">
    <h2 class="text-center">
      Welcome {{user.username}}
       </h2>
       <br/>
       <br/>
    
    <div class="container">
        
     <div class="text-center">
        
      <div class="align-items-center ">

        <div class="rounded-circle overflow-hidden" style="width: 150px;height: 150px;margin-left: 94px;">
        {% if userprofile.profile_picture %}
          <img src="{{ userprofile.profile_picture.url }}" alt="{{ user.username }}" class="w-100 h-100 object-fit-cover">
        {% else %}
          <i class="fas fa-user fa-3x text-muted"></i>
        {% endif %}
        </div>
    
        
        <form method="POST" action="{% url 'userprofile'%}" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="ms-3">
          <label for="id_profile_picture" class="btn btn-primary mt-2">
            <i class="fas fa-upload"></i> Upload Picture
          </label>
          <input type="file" name="profile_picture" id="id_profile_picture" class="visually-hidden">
          <button type="submit" class="btn btn-success mt-2">
            <i class="fas fa-check"></i> Save Changes
          </button>
        </div>
          <div class="form-floating mb-3 mt-4">
            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com" value="{{ user.email }}" disabled>
            <label for="floatingInput">Email address</label>
          </div>
          <div class="form-floating mb-3 mt-4">
            <input type="text" class="form-control" id="floatingInput"  value="{{ user.username }}" disabled>
            <label for="floatingInput">User Name</label>
          </div>
          <div class="form-floating mb-3 mt-4">
            <input type="text" class="form-control" id="floatingInput" name="phone_number" value="{{ user.phone_number }}" >
            <label for="floatingInput">Phone No</label>
          </div>
          <div class="form-floating mb-3 mt-4">
            <input type="text" class="form-control" id="floatingInput" name="adress_line_1" value="{{ userprofile.adress_line_1 }}" >
            <label for="floatingInput">Address</label>
          </div>
          <div class="form-floating mb-3 mt-4">
            <input type="text" class="form-control" id="floatingInput" name="state"  value="{{ userprofile.state }}" >
            <label for="floatingInput">State</label>
          </div>
          <div class="form-floating mb-3 mt-4">
            <input type="text" class="form-control" id="floatingInput" name="pin_code" value="{{ userprofile.pin_code }}" >
            <label for="floatingInput"> Zip Code</label>
          </div>
          <div class="form-floating mb-3 mt-4">
            <input type="text" class="form-control" id="floatingInput" name="city" value="{{ userprofile.city }}" >
            <label for="floatingInput">City</label>
          </div>
         
        </form>
        
    </div>
    
  </div>
</div>
   
  </section>
   <!-- alertify -->
   <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>

  {% for msg in messages %}
  <script>   
  
  
  
    alertify.set('notifier','position', 'top-right');
    alertify.message('{{msg}}');
    </script>
  {%endfor%}
  

  
  
  <script>
    const body = document.querySelector('body'),
      sidebar = body.querySelector('nav'),
      toggle = body.querySelector(".toggle"),
      searchBtn = body.querySelector(".search-box"),
      modeSwitch = body.querySelector(".toggle-switch"),
      modeText = body.querySelector(".mode-text");
    toggle.addEventListener("click", () => {
      sidebar.classList.toggle("close");
    })
    searchBtn.addEventListener("click", () => {
      sidebar.classList.remove("close");
    })
    modeSwitch.addEventListener("click", () => {
      body.classList.toggle("dark");
      if (body.classList.contains("dark")) {
        modeText.innerText = "Light mode";
      } else {
        modeText.innerText = "Dark mode";
      }
    });

    // profile picutre
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  <!-- Bootstrap -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <!-- Bootstrap -->

</body>

</html>